# Generated by Django 2.1.7 on 2019-03-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('current_job', models.CharField(max_length=200)),
                ('current_company', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
