# Generated by Django 2.1.7 on 2019-03-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_awardscertifications_education_projects_volunteerexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='skill_summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
